### ISSUE TITLE
Add an option to prevent reformatting the whole Dotbot configuration file

### ISSUE THREAD

**Issue by nagromc** [gwerbin/dotbot-autobot#4]
When I use `autobot` hook, the whole `install.conf.yaml` is reformatted:

``` shell
$ cat install.conf.yaml
- defaults:
    link:
      create: true

- clean:
    - '~'

- link:
    ~/.vimrc: vim/vimrc
    # An awesome comment
    ~/.dotfiles: ''

- shell:
    - [echo hello world, A shell command]
$ yamllint install.conf.yaml
install.conf.yaml
  1:1       warning  missing document start "---"  (document-start)

$ # this is a valid install.conf.yaml
$ echo "test" > test.txt
$ git add .
$ git commit -m "Test the awesome autobot hook ;-)"
$ # autobot ran successfully
$ cat install.conf.yaml
- defaults:
    link:
      create: true
- clean:
  - '~'
- link:
    ~/.dotfiles: ''
    ~/.vimrc: vim/vimrc
- shell:
  - - echo hello world
    - A shell command
- link:
    ~/.test.txt: .test.txt
```

I have several remarks about the reformatting:
- the comment `# An awesome comment` disappeared
- entries in the first `link` section have been sorted
- the shell entries have been exploded on two lines
- the initial indentation has been replaced

**Comment by gwerbin** [comment]
Sorry @nagromc I totally forgot about this -- still getting used to working on open-source projects like this.

Yes, that was a deliberate design decision in order to get the MVP working. This works by parsing the YAML into a Python object, appending to that object, and re-dumping the new YAML back out. I should have made this clear in the documentation.

A better idea might be to just ignore the existing YAML, create new objects, and just append those objects to the existing config file. What do you think?

**Comment by nagromc** [comment]
No problem @gwerbin, we all have a couple of projects to work on ;-)

Yes it would be a good idea to make it clear in the documentation. Regarding your suggestion, I don't know that much Python so I cannot answer. From my point of view, maybe it seems a bit complicated, but if you manage to do it without much effort, yes why not!

Another solution may be to let the user configure -- if it is allowed by `pyaml` -- how he wants to format his `install.conf.yaml`:

- keeping the original sorting of the entries. Maybe `pyaml` parses the `install.conf.yaml` entries as sorted lists
- choosing the list style (the `[`-`,`-`]` style or splitted lists style). Of course, this will be consistent throughout the file
- setting the indentation style

I understand comments will be ignored by the parser, thus not dumped back in the file.

**Comment by gwerbin** [comment]
@nagromc I don't think I'm going to end up having the time to do this. I still use Dotbot but this was never a tool that fit into my workflow. Feel free to fork, you can have it :)
